# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    goals: 'package'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'nginx-dev-con'
    sourceFolder: '$(Agent.BuildDirectory)'
    contents: '**/*.jar'
    targetFolder: '/opt/tomcat/webapps/'
    readyTimeout: '20000'
    flattenFolders: true

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'nginx-dev-con'
    sourceFolder: '$(Agent.BuildDirectory)'
    contents: '**'
    targetFolder: '/opt/tomcat/webapps/'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'nginx-dev-con'
    runOptions: 'commands'
    commands: |
      /opt/tomcat/bin/shutdown.sh
      /opt/tomcat/bin/startup.sh
    readyTimeout: '20000'