# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install nginx -y
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo cp target/**/*.jar /var/www/html/

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo service nginx start
