# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'nginx-dev-con'
    sourceFolder: '$(Agent.BuildDirectory'
    contents: '**/*.war'
    targetFolder: '/var/www/html/'
    readyTimeout: '20000'
    flattenFolders: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo service nginx stop
      sudo service nginx start